set(_CATKIN_CURRENT_PACKAGE "Distance_Sensor")
set(Distance_Sensor_VERSION "0.0.0")
set(Distance_Sensor_MAINTAINER "gian <gian@todo.todo>")
set(Distance_Sensor_PACKAGE_FORMAT "1")
set(Distance_Sensor_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_generation")
set(Distance_Sensor_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(Distance_Sensor_BUILDTOOL_DEPENDS "catkin")
set(Distance_Sensor_BUILDTOOL_EXPORT_DEPENDS )
set(Distance_Sensor_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(Distance_Sensor_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(Distance_Sensor_TEST_DEPENDS )
set(Distance_Sensor_DOC_DEPENDS )
set(Distance_Sensor_URL_WEBSITE "")
set(Distance_Sensor_URL_BUGTRACKER "")
set(Distance_Sensor_URL_REPOSITORY "")
set(Distance_Sensor_DEPRECATED "")