set(_CATKIN_CURRENT_PACKAGE "optimal_walk")
set(optimal_walk_VERSION "0.0.0")
set(optimal_walk_MAINTAINER "gian <gian@todo.todo>")
set(optimal_walk_PACKAGE_FORMAT "1")
set(optimal_walk_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_generation")
set(optimal_walk_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(optimal_walk_BUILDTOOL_DEPENDS "catkin")
set(optimal_walk_BUILDTOOL_EXPORT_DEPENDS )
set(optimal_walk_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(optimal_walk_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(optimal_walk_TEST_DEPENDS )
set(optimal_walk_DOC_DEPENDS )
set(optimal_walk_URL_WEBSITE "")
set(optimal_walk_URL_BUGTRACKER "")
set(optimal_walk_URL_REPOSITORY "")
set(optimal_walk_DEPRECATED "")