set(_CATKIN_CURRENT_PACKAGE "zmp_walk_gui")
set(zmp_walk_gui_VERSION "0.0.0")
set(zmp_walk_gui_MAINTAINER "gian <gian@todo.todo>")
set(zmp_walk_gui_PACKAGE_FORMAT "1")
set(zmp_walk_gui_BUILD_DEPENDS "geometry_msgs" "message_generation" "roscpp" "rospy" "std_msgs" "message_generation")
set(zmp_walk_gui_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(zmp_walk_gui_BUILDTOOL_DEPENDS "catkin")
set(zmp_walk_gui_BUILDTOOL_EXPORT_DEPENDS )
set(zmp_walk_gui_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(zmp_walk_gui_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(zmp_walk_gui_TEST_DEPENDS )
set(zmp_walk_gui_DOC_DEPENDS )
set(zmp_walk_gui_URL_WEBSITE "")
set(zmp_walk_gui_URL_BUGTRACKER "")
set(zmp_walk_gui_URL_REPOSITORY "")
set(zmp_walk_gui_DEPRECATED "")