set(_CATKIN_CURRENT_PACKAGE "qb_chain_control")
set(qb_chain_control_VERSION "0.1.3")
set(qb_chain_control_MAINTAINER "Alessandro Tondo <alessandro.tondo@qbrobotics.com>")
set(qb_chain_control_PACKAGE_FORMAT "2")
set(qb_chain_control_BUILD_DEPENDS )
set(qb_chain_control_BUILD_EXPORT_DEPENDS )
set(qb_chain_control_BUILDTOOL_DEPENDS "catkin")
set(qb_chain_control_BUILDTOOL_EXPORT_DEPENDS )
set(qb_chain_control_EXEC_DEPENDS )
set(qb_chain_control_RUN_DEPENDS )
set(qb_chain_control_TEST_DEPENDS )
set(qb_chain_control_DOC_DEPENDS )
set(qb_chain_control_URL_WEBSITE "http://wiki.ros.org/qb_chain_control")
set(qb_chain_control_URL_BUGTRACKER "https://bitbucket.org/qbrobotics/qbchain-ros/issues")
set(qb_chain_control_URL_REPOSITORY "https://bitbucket.org/qbrobotics/qbchain-ros")
set(qb_chain_control_DEPRECATED "")