set(_CATKIN_CURRENT_PACKAGE "synergies")
set(synergies_VERSION "0.0.0")
set(synergies_MAINTAINER "gian <gian@todo.todo>")
set(synergies_PACKAGE_FORMAT "1")
set(synergies_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_generation")
set(synergies_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(synergies_BUILDTOOL_DEPENDS "catkin")
set(synergies_BUILDTOOL_EXPORT_DEPENDS )
set(synergies_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(synergies_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(synergies_TEST_DEPENDS )
set(synergies_DOC_DEPENDS )
set(synergies_URL_WEBSITE "")
set(synergies_URL_BUGTRACKER "")
set(synergies_URL_REPOSITORY "")
set(synergies_DEPRECATED "")