set(_CATKIN_CURRENT_PACKAGE "save_qb_legs")
set(save_qb_legs_VERSION "0.0.0")
set(save_qb_legs_MAINTAINER "gian <gian@todo.todo>")
set(save_qb_legs_PACKAGE_FORMAT "1")
set(save_qb_legs_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(save_qb_legs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(save_qb_legs_BUILDTOOL_DEPENDS "catkin")
set(save_qb_legs_BUILDTOOL_EXPORT_DEPENDS )
set(save_qb_legs_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(save_qb_legs_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(save_qb_legs_TEST_DEPENDS )
set(save_qb_legs_DOC_DEPENDS )
set(save_qb_legs_URL_WEBSITE "")
set(save_qb_legs_URL_BUGTRACKER "")
set(save_qb_legs_URL_REPOSITORY "")
set(save_qb_legs_DEPRECATED "")