set(_CATKIN_CURRENT_PACKAGE "qb_chain")
set(qb_chain_VERSION "0.1.3")
set(qb_chain_MAINTAINER "Alessandro Tondo <alessandro.tondo@qbrobotics.com>")
set(qb_chain_PACKAGE_FORMAT "2")
set(qb_chain_BUILD_DEPENDS )
set(qb_chain_BUILD_EXPORT_DEPENDS )
set(qb_chain_BUILDTOOL_DEPENDS "catkin")
set(qb_chain_BUILDTOOL_EXPORT_DEPENDS )
set(qb_chain_EXEC_DEPENDS "qb_chain_control" "qb_chain_description")
set(qb_chain_RUN_DEPENDS "qb_chain_control" "qb_chain_description")
set(qb_chain_TEST_DEPENDS )
set(qb_chain_DOC_DEPENDS )
set(qb_chain_URL_WEBSITE "http://wiki.ros.org/qb_chain")
set(qb_chain_URL_BUGTRACKER "https://bitbucket.org/qbrobotics/qbchain-ros/issues")
set(qb_chain_URL_REPOSITORY "https://bitbucket.org/qbrobotics/qbchain-ros")
set(qb_chain_DEPRECATED "")