# This YAML file must contains the configuration of each mesh to properly build the URDF automagically.
# The aim of this additional file is to encapsulate all the physical properties in a single place without hiding them
# in a long URDF structure.
#
# Note: there is no need to modify this file unless you hack the qbhand physical mechanism. Nonetheless it is
#       recommended to create a distinct YAML file for each version of the qbhand (this helps with versioning and
#       leaves the default configuration as is).
#
# Brief description:
# * The `default` group holds the anchors for the common default settings, i.e. avoid annoying repetitions.
# * The `qb_hand` group contains the current properties to build the URDF correctly.

default:
  parameters:
    axis_abduction: &axis_abduction ""
    axis_flexion: &axis_flexion ""
    dynamics: &dynamics
      damping:
      friction:
    effort_limit: &effort
    velocity_limit: &velocity
    virtual_mechanism: &virtual_mechanism
      position: "0.013 0 0"
      orientation: "0 0 0"

  finger:
    knuckle: &knuckle
#      position: ""
#      orientation: ""
      axis: *axis_abduction
      mimic_reduction: 1.0
      dynamics: *dynamics
      limits:
        lower: 
        upper: 
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 
        origin: ""
        inertia:
          ixx: 
          ixy: 
          ixz: 
          iyy: 
          iyz: 
          izz:

    proximal: &proximal
      position: "0.009 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 1.0
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 
        upper: 
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 
        origin: ""
        inertia:
          ixx: 
          ixy: 
          ixz: 
          iyy: 
          iyz: 
          izz:

    middle: &middle
      position: "0.009 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 1.0
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 
        upper: 
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 
        origin: ""
        inertia:
          ixx: 
          ixy: 
          ixz: 
          iyy: 
          iyz: 
          izz:

    distal: &distal
      position: "0.009 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 1.0
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 
        upper: 
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 
        origin: ""
        inertia:
          ixx: 
          ixy: 
          ixz: 
          iyy: 
          iyz: 
          izz:


qb_hand:
  right_base:
    position: ""
    orientation: ""
    inertial:
      mass:
      origin: ""
      inertia:
        ixx:
        ixy:
        ixz:
        iyy:
        iyz:
        izz:

  right_palm:
    position: ""
    orientation: ""
    inertial:
      mass:
      origin: ""
      inertia:
        ixx:
        ixy:
        ixz:
        iyy:
        iyz:
        izz:

  single_synergy:
    axis: "0 0 1"  # it is not important though
    dynamics: *dynamics
    limits:
      lower: 0.0
      upper: 1.0
      effort: *effort
      velocity: *velocity

  # all fingers have the same base structure and only few things change among them (e.g. the pose of the knuckle)
  thumb:
    knuckle:
      << : *knuckle
      position: ""
      orientation: ""
    middle: *middle
    distal: *distal

  index:
    knuckle:
      << : *knuckle
      position: ""
      orientation: ""
    proximal: *proximal
    middle: *middle
    distal: *distal

  middle:
    knuckle:
      << : *knuckle
      position: ""
      orientation: ""
    proximal: *proximal
    middle: *middle
    distal: *distal

  ring:
    knuckle:
      << : *knuckle
      position: ""
      orientation: ""
    proximal: *proximal
    middle: *middle
    distal: *distal

  little:
    knuckle:
      << : *knuckle
      position: ""
      orientation: ""
    proximal: *proximal
    middle: *middle
    distal: *distal