set(_CATKIN_CURRENT_PACKAGE "qb_move_hardware_interface")
set(qb_move_hardware_interface_VERSION "0.7.7")
set(qb_move_hardware_interface_MAINTAINER "Alessandro Tondo <alessandro.tondo@qbrobotics.com>")
set(qb_move_hardware_interface_PACKAGE_FORMAT "2")
set(qb_move_hardware_interface_BUILD_DEPENDS "roscpp" "transmission_interface" "qb_device_hardware_interface")
set(qb_move_hardware_interface_BUILD_EXPORT_DEPENDS "roscpp" "transmission_interface" "qb_device_hardware_interface")
set(qb_move_hardware_interface_BUILDTOOL_DEPENDS "catkin")
set(qb_move_hardware_interface_BUILDTOOL_EXPORT_DEPENDS )
set(qb_move_hardware_interface_EXEC_DEPENDS "roscpp" "transmission_interface" "qb_device_hardware_interface")
set(qb_move_hardware_interface_RUN_DEPENDS "roscpp" "transmission_interface" "qb_device_hardware_interface")
set(qb_move_hardware_interface_TEST_DEPENDS )
set(qb_move_hardware_interface_DOC_DEPENDS "doxygen")
set(qb_move_hardware_interface_URL_WEBSITE "http://wiki.ros.org/qb_move_hardware_interface")
set(qb_move_hardware_interface_URL_BUGTRACKER "https://bitbucket.org/qbrobotics/qbmove-ros/issues")
set(qb_move_hardware_interface_URL_REPOSITORY "https://bitbucket.org/qbrobotics/qbmove-ros")
set(qb_move_hardware_interface_DEPRECATED "")