set(_CATKIN_CURRENT_PACKAGE "qb_chain_description")
set(qb_chain_description_VERSION "0.1.3")
set(qb_chain_description_MAINTAINER "Alessandro Tondo <alessandro.tondo@qbrobotics.com>")
set(qb_chain_description_PACKAGE_FORMAT "2")
set(qb_chain_description_BUILD_DEPENDS )
set(qb_chain_description_BUILD_EXPORT_DEPENDS )
set(qb_chain_description_BUILDTOOL_DEPENDS "catkin")
set(qb_chain_description_BUILDTOOL_EXPORT_DEPENDS )
set(qb_chain_description_EXEC_DEPENDS )
set(qb_chain_description_RUN_DEPENDS )
set(qb_chain_description_TEST_DEPENDS )
set(qb_chain_description_DOC_DEPENDS )
set(qb_chain_description_URL_WEBSITE "http://wiki.ros.org/qb_chain_description")
set(qb_chain_description_URL_BUGTRACKER "https://bitbucket.org/qbrobotics/qbchain-ros/issues")
set(qb_chain_description_URL_REPOSITORY "https://bitbucket.org/qbrobotics/qbchain-ros")
set(qb_chain_description_DEPRECATED "")