set(_CATKIN_CURRENT_PACKAGE "qb_move_description")
set(qb_move_description_VERSION "0.7.7")
set(qb_move_description_MAINTAINER "Alessandro Tondo <alessandro.tondo@qbrobotics.com>")
set(qb_move_description_PACKAGE_FORMAT "2")
set(qb_move_description_BUILD_DEPENDS )
set(qb_move_description_BUILD_EXPORT_DEPENDS )
set(qb_move_description_BUILDTOOL_DEPENDS "catkin")
set(qb_move_description_BUILDTOOL_EXPORT_DEPENDS )
set(qb_move_description_EXEC_DEPENDS )
set(qb_move_description_RUN_DEPENDS )
set(qb_move_description_TEST_DEPENDS )
set(qb_move_description_DOC_DEPENDS )
set(qb_move_description_URL_WEBSITE "http://wiki.ros.org/qb_move_description")
set(qb_move_description_URL_BUGTRACKER "https://bitbucket.org/qbrobotics/qbmove-ros/issues")
set(qb_move_description_URL_REPOSITORY "https://bitbucket.org/qbrobotics/qbmove-ros")
set(qb_move_description_DEPRECATED "")