set(_CATKIN_CURRENT_PACKAGE "qb_legs_gui")
set(qb_legs_gui_VERSION "0.0.0")
set(qb_legs_gui_MAINTAINER "gian <gian@todo.todo>")
set(qb_legs_gui_PACKAGE_FORMAT "1")
set(qb_legs_gui_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(qb_legs_gui_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(qb_legs_gui_BUILDTOOL_DEPENDS "catkin")
set(qb_legs_gui_BUILDTOOL_EXPORT_DEPENDS )
set(qb_legs_gui_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(qb_legs_gui_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(qb_legs_gui_TEST_DEPENDS )
set(qb_legs_gui_DOC_DEPENDS )
set(qb_legs_gui_URL_WEBSITE "")
set(qb_legs_gui_URL_BUGTRACKER "")
set(qb_legs_gui_URL_REPOSITORY "")
set(qb_legs_gui_DEPRECATED "")