set(_CATKIN_CURRENT_PACKAGE "qb_move")
set(qb_move_VERSION "0.7.7")
set(qb_move_MAINTAINER "Alessandro Tondo <alessandro.tondo@qbrobotics.com>")
set(qb_move_PACKAGE_FORMAT "2")
set(qb_move_BUILD_DEPENDS )
set(qb_move_BUILD_EXPORT_DEPENDS )
set(qb_move_BUILDTOOL_DEPENDS "catkin")
set(qb_move_BUILDTOOL_EXPORT_DEPENDS )
set(qb_move_EXEC_DEPENDS "qb_move_control" "qb_move_description" "qb_move_hardware_interface")
set(qb_move_RUN_DEPENDS "qb_move_control" "qb_move_description" "qb_move_hardware_interface")
set(qb_move_TEST_DEPENDS )
set(qb_move_DOC_DEPENDS )
set(qb_move_URL_WEBSITE "http://wiki.ros.org/qb_move")
set(qb_move_URL_BUGTRACKER "https://bitbucket.org/qbrobotics/qbmove-ros/issues")
set(qb_move_URL_REPOSITORY "https://bitbucket.org/qbrobotics/qbmove-ros")
set(qb_move_DEPRECATED "")