set(_CATKIN_CURRENT_PACKAGE "qb_move_control")
set(qb_move_control_VERSION "0.7.7")
set(qb_move_control_MAINTAINER "Alessandro Tondo <alessandro.tondo@qbrobotics.com>")
set(qb_move_control_PACKAGE_FORMAT "2")
set(qb_move_control_BUILD_DEPENDS "roscpp" "qb_device_control" "qb_move_hardware_interface")
set(qb_move_control_BUILD_EXPORT_DEPENDS "roscpp" "qb_device_control" "qb_move_hardware_interface")
set(qb_move_control_BUILDTOOL_DEPENDS "catkin")
set(qb_move_control_BUILDTOOL_EXPORT_DEPENDS )
set(qb_move_control_EXEC_DEPENDS "roscpp" "qb_device_control" "qb_move_hardware_interface")
set(qb_move_control_RUN_DEPENDS "roscpp" "qb_device_control" "qb_move_hardware_interface")
set(qb_move_control_TEST_DEPENDS )
set(qb_move_control_DOC_DEPENDS "doxygen")
set(qb_move_control_URL_WEBSITE "http://wiki.ros.org/qb_move_control")
set(qb_move_control_URL_BUGTRACKER "https://bitbucket.org/qbrobotics/qbmove-ros/issues")
set(qb_move_control_URL_REPOSITORY "https://bitbucket.org/qbrobotics/qbmove-ros")
set(qb_move_control_DEPRECATED "")