set(_CATKIN_CURRENT_PACKAGE "qb_ctrl_voltage")
set(qb_ctrl_voltage_VERSION "0.0.0")
set(qb_ctrl_voltage_MAINTAINER "gian <gian@todo.todo>")
set(qb_ctrl_voltage_PACKAGE_FORMAT "2")
set(qb_ctrl_voltage_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(qb_ctrl_voltage_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(qb_ctrl_voltage_BUILDTOOL_DEPENDS "catkin")
set(qb_ctrl_voltage_BUILDTOOL_EXPORT_DEPENDS )
set(qb_ctrl_voltage_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(qb_ctrl_voltage_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(qb_ctrl_voltage_TEST_DEPENDS )
set(qb_ctrl_voltage_DOC_DEPENDS )
set(qb_ctrl_voltage_URL_WEBSITE "")
set(qb_ctrl_voltage_URL_BUGTRACKER "")
set(qb_ctrl_voltage_URL_REPOSITORY "")
set(qb_ctrl_voltage_DEPRECATED "")