set(_CATKIN_CURRENT_PACKAGE "zmp_walk")
set(zmp_walk_VERSION "0.0.0")
set(zmp_walk_MAINTAINER "gian <gian@todo.todo>")
set(zmp_walk_PACKAGE_FORMAT "1")
set(zmp_walk_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(zmp_walk_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(zmp_walk_BUILDTOOL_DEPENDS "catkin")
set(zmp_walk_BUILDTOOL_EXPORT_DEPENDS )
set(zmp_walk_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(zmp_walk_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(zmp_walk_TEST_DEPENDS )
set(zmp_walk_DOC_DEPENDS )
set(zmp_walk_URL_WEBSITE "")
set(zmp_walk_URL_BUGTRACKER "")
set(zmp_walk_URL_REPOSITORY "")
set(zmp_walk_DEPRECATED "")