cube1_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube1_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube1_shaft_joint
    - cube1_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube1_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube1_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube1_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube1_motor_1_joint
    - cube1_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube1_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube1_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube2_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube2_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube2_shaft_joint
    - cube2_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube2_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube2_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube2_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube2_motor_1_joint
    - cube2_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube2_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube2_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube3_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube3_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube3_shaft_joint
    - cube3_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube3_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube3_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube3_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube3_motor_1_joint
    - cube3_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube3_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube3_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube4_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube4_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube4_shaft_joint
    - cube4_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube4_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube4_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube4_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube4_motor_1_joint
    - cube4_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube4_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube4_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube5_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube5_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube5_shaft_joint
    - cube5_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube5_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube5_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube5_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube5_motor_1_joint
    - cube5_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube5_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube5_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube22_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube22_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube22_shaft_joint
    - cube22_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube22_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube22_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube22_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube22_motor_1_joint
    - cube22_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube22_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube22_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube11_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube11_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube11_shaft_joint
    - cube11_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube11_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube11_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube11_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube11_motor_1_joint
    - cube11_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube11_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube11_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube12_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube12_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube12_shaft_joint
    - cube12_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube12_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube12_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube12_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube12_motor_1_joint
    - cube12_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube12_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube12_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube13_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube13_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube13_shaft_joint
    - cube13_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube13_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube13_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube13_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube13_motor_1_joint
    - cube13_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube13_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube13_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube14_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube14_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube14_shaft_joint
    - cube14_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube14_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube14_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube14_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube14_motor_1_joint
    - cube14_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube14_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube14_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube15_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube15_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube15_shaft_joint
    - cube15_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube15_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube15_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube15_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube15_motor_1_joint
    - cube15_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube15_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube15_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube21_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube21_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube21_shaft_joint
    - cube21_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube21_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube21_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube21_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube21_motor_1_joint
    - cube21_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube21_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube21_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0
