cube11_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube11_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube11_shaft_joint
    - cube11_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube11_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube11_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube11_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube11_motor_1_joint
    - cube11_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube11_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube11_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube12_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube12_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube12_shaft_joint
    - cube12_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube12_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube12_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube12_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube12_motor_1_joint
    - cube12_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube12_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube12_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube13_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube13_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube13_shaft_joint
    - cube13_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube13_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube13_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube13_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube13_motor_1_joint
    - cube13_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube13_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube13_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube14_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube14_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube14_shaft_joint
    - cube14_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube14_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube14_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube14_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube14_motor_1_joint
    - cube14_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube14_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube14_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube15_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube15_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube15_shaft_joint
    - cube15_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube15_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube15_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube15_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube15_motor_1_joint
    - cube15_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube15_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube15_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

cube21_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbmove with shaft reference position and stiffness preset
cube21_position_and_preset_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube21_shaft_joint
    - cube21_stiffness_preset_virtual_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube21_shaft_joint:
      trajectory: 0.1
      goal: 0.05
    cube21_stiffness_preset_virtual_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0

# control the qbmove with motor positions
cube21_motor_positions_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - cube21_motor_1_joint
    - cube21_motor_2_joint
  constraints:
    goal_time: 0.2
    stopped_velocity_tolerance: 0.1
    cube21_motor_1_joint:
      trajectory: 0.1
      goal: 0.05
    cube21_motor_2_joint:
      trajectory: 0.1
      goal: 0.05
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0