set(_CATKIN_CURRENT_PACKAGE "qb_frank_controller")
set(qb_frank_controller_VERSION "0.0.0")
set(qb_frank_controller_MAINTAINER "ale <ale@todo.todo>")
set(qb_frank_controller_PACKAGE_FORMAT "1")
set(qb_frank_controller_BUILD_DEPENDS "roscpp" "roslib")
set(qb_frank_controller_BUILD_EXPORT_DEPENDS "roscpp" "roslib")
set(qb_frank_controller_BUILDTOOL_DEPENDS "catkin")
set(qb_frank_controller_BUILDTOOL_EXPORT_DEPENDS )
set(qb_frank_controller_EXEC_DEPENDS "roscpp" "roslib")
set(qb_frank_controller_RUN_DEPENDS "roscpp" "roslib")
set(qb_frank_controller_TEST_DEPENDS )
set(qb_frank_controller_DOC_DEPENDS )
set(qb_frank_controller_URL_WEBSITE "")
set(qb_frank_controller_URL_BUGTRACKER "")
set(qb_frank_controller_URL_REPOSITORY "")
set(qb_frank_controller_DEPRECATED "")